spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lunch_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: spartaroot1234
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: kr.sparta.backend1.lunch.dto
  configuration:
    map-underscore-to-camel-case: true
